# Run during the 'gulp build' command
# Overrides these options in _config.yml

# Overrides the default URL, needed for your atom feed and sitemap
url: https://github.com/ucsf-web-services/shoestring
baseurl: /shoestring
# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
lsi: true
# Removes the upper limit for posts generated
limit_posts: 0

source: 'docs'
destination: '_gh_pages'

repo: https://github.com/ucsf-web-services/shoestring